return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 15,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 8,
  nextobjectid = 33,
  properties = {
    ["border"] = "undertale/fire",
    ["light"] = true,
    ["music"] = "core"
  },
  tilesets = {
    {
      name = "core",
      firstgid = 1,
      filename = "../../tilesets/core.tsx",
      exportfilename = "../../tilesets/core.lua"
    },
    {
      name = "corestuff",
      firstgid = 361,
      filename = "../../tilesets/corestuff.tsx",
      exportfilename = "../../tilesets/corestuff.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 15,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        55, 56, 56, 57, 19, 0, 0, 0, 0, 0, 0, 21, 55, 56, 56, 57,
        55, 56, 56, 57, 37, 38, 38, 38, 38, 38, 38, 39, 55, 56, 56, 57,
        55, 0, 0, 57, 55, 56, 56, 56, 56, 56, 56, 57, 55, 0, 0, 57,
        73, 0, 0, 75, 55, 56, 56, 56, 56, 56, 56, 57, 73, 0, 0, 75,
        0, 4, 6, 0, 55, 56, 56, 56, 56, 56, 56, 57, 0, 4, 6, 0,
        3, 22, 24, 0, 55, 56, 56, 0, 0, 56, 56, 57, 0, 22, 24, 1,
        21, 22, 24, 0, 55, 96, 96, 0, 0, 96, 96, 80, 0, 22, 24, 19,
        21, 22, 23, 5, 23, 23, 23, 23, 23, 23, 23, 23, 5, 23, 24, 19,
        21, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 19,
        21, 40, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 42, 19,
        0, 3, 40, 41, 41, 41, 41, 23, 23, 41, 41, 41, 41, 42, 1, 0,
        0, 0, 2, 2, 2, 2, 3, 22, 24, 1, 2, 2, 2, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 21, 22, 24, 19, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 21, 22, 24, 19, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 21, 22, 24, 19, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 15,
      id = 2,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 281, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 281, 300, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        27, 0, 0, 30, 0, 280, 0, 0, 0, 0, 283, 0, 27, 0, 0, 30,
        45, 0, 0, 48, 0, 298, 0, 178, 179, 0, 301, 0, 45, 0, 0, 48,
        0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 283, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 298, 0, 0, 0, 0, 301, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 73, 0, 0, 0, 0, 0, 0, 75, 0, 0, 0, 0,
        0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0,
        0, 263, 263, 265, 280, 0, 0, 262, 265, 0, 0, 280, 262, 264, 263, 0,
        0, 0, 0, 283, 280, 0, 0, 316, 319, 0, 0, 280, 280, 0, 0, 0,
        0, 0, 0, 301, 280, 0, 0, 0, 0, 0, 0, 280, 298, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 263, 264, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 20,
          y = 160,
          width = 120,
          height = 120,
          rotation = 0,
          gid = 371,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 500,
          y = 160,
          width = 120,
          height = 120,
          rotation = 0,
          gid = 371,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 252,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 413,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 132,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 413,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 132,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 413,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 252,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 419,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 252,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 419,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 252,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 419,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 252,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 419,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 252,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 425,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 132,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 425,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 132,
          width = 40,
          height = 12,
          rotation = 0,
          gid = 425,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 180,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 180,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 146,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 240,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 240,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 160,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 160,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 160,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 440,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 440,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 440,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 28,
          name = "elevatordoor",
          type = "",
          shape = "rectangle",
          x = 260,
          y = 240,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 230,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "hotland/core_premett",
            ["marker"] = "elevator"
          }
        },
        {
          id = 31,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 570,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "hotland/precore",
            ["marker"] = "north"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 13,
          name = "spawn",
          type = "",
          shape = "point",
          x = 320,
          y = 420,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "elevator",
          type = "",
          shape = "point",
          x = 320,
          y = 310,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "south",
          type = "",
          shape = "point",
          x = 320,
          y = 530,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
